Add and randomize choices with correct and wrong answers
VicDosya/geo-trainer pull request #4
Opened 2022-10-27 21:39 UTC by VicDosya

![image](https://user-images.githubusercontent.com/96661032/198403059-59a26b28-3404-40fd-9825-2220d184396b.png)

I'm having trouble with choices:
Whenever I choose the wrong answer, the choices scramble. I need help sorting them outside the res.send object in app.get('/quiz').

2022-10-28 12:25 UTC, VicDosya commented
Actually nevermind, it works just fine. 
the flag and choices change when i press the correct choice.
the choices dont scramble when i choose wrong choice ( which is good ).

2022-10-28 16:29 UTC, VicDosya commented
![image](https://user-images.githubusercontent.com/96661032/198686691-754ecff4-ab22-48e7-b887-71f90cec6ac1.png)

sometimes the game stops to function correctly, i'm going to need u to review this lol...

2022-10-30 20:43 UTC, 8o8inCodes requested changes

2022-10-30 20:43 UTC, 8o8inCodes commented on client/src/components/Trainer.js
> +        if (res.data.correctStatus != true) {
```js
if (!res.data.correctStatus) {
```

2022-10-30 20:43 UTC, 8o8inCodes commented on server/api/flag-trainer.js
> +    retryCount++
You need to send the retryCount to the function, otherwise retryCount is useless and theoretically the function will always keep trying, infinitely. as long as the randomFlag is equal to the correct flag.

```js
randomFlagNumber(retryCount+1)
```

2022-10-30 20:43 UTC, 8o8inCodes commented on server/api/flag-trainer.js
> +    ].sort((a, b) => 0.5 - Math.random()),   //Randomise the positioning of the choices
randomFlagNumber already generates it randomly, so no need to sort it randomly again.

2022-10-30 20:43 UTC, 8o8inCodes commented on server/api/flag-trainer.js
> +    correctFlagNumber = Math.floor(Math.random() * 242) + 1;
Extract it to a function, because you're using same logic twice already

2022-11-03 11:24 UTC, VicDosya commented on server/api/flag-trainer.js
> +    ].sort((a, b) => 0.5 - Math.random()),   //Randomise the positioning of the choices
Well then the user will choose the third option all the time for the correct answer..
The sort is for sorting the array itself to randomize the position of the choices.

2022-11-03 11:57 UTC, VicDosya commented on server/api/flag-trainer.js
> +    correctFlagNumber = Math.floor(Math.random() * 242) + 1;
It's not working with a function ;_;

2022-11-03 16:15 UTC, 8o8inCodes commented on server/api/flag-trainer.js
> +    ].sort((a, b) => 0.5 - Math.random()),   //Randomise the positioning of the choices
Good point

2022-11-05 12:02 UTC, 8o8inCodes commented on server/api/flag-trainer.js
> +    correctFlagNumber = Math.floor(Math.random() * 242) + 1;
```js
// Make sure this function is defined above most of the code where it's gonna be used
const generateRandomFlagNumber = () => Math.floor(Math.random() * 242) + 1;

// in line 52
correctFlagNumber = generateRandomFlagNumber()
```

2022-11-06 13:05 UTC, 8o8inCodes approved these changes

2022-11-06 13:16 UTC, merged